# Generated by Django 4.1.7 on 2023-03-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tags',
        ),
    ]
