# Generated by Django 4.1.7 on 2023-04-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_descripcion_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tarifa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
