# Generated by Django 4.1.7 on 2023-06-07 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('estado', models.CharField(default='Creado', max_length=10)),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(null=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuente', to=settings.AUTH_USER_MODEL)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titular', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
