# Generated by Django 4.1.7 on 2023-05-30 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0003_rename_nombre_tutoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
