# Generated by Django 4.1.7 on 2023-05-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0004_tutoria_duracion_tutoria_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoria',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
