# Generated by Django 4.1.7 on 2023-04-12 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0003_rename_nombre_tutoria_nombre_and_more'),
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='tutoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutoria', to='tutorias.tutoria'),
        ),
    ]
